### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by fangzhangmnm** [therainisme/vscode-clear-markdown-unused-images#3]
1. It removes all the used images
2. Expect it to work for the current file, but it instead deal with all the files in the workspace
3. if the used images have the same name, they override each other

combining 123 means it messed up all my project. Hope one can fix those dangerous issues

**Comment by therainisme** [comment]
I'm sorry it messed up your project. I think we should be able to provide an undo function.

It is expected to scan the entire workspace and remove any unused images, since many images referenced by markdown are not actually in the same directory as the markdown. 

3 is indeed a bug. 

Thanks for your feedback, I will fix these bugs soon.

**Comment by fangzhangmnm** [comment]
I think one possible reason is the extension of my code is .txt, although I switched its language mode to markdown in vs code.

btw don't worry the damage is not very big. but the bug 3 is indeed have potential to cause a very big trouble.

update:
I just verified the problem occurs on a .md file, not .txt
